### ISSUE TITLE
SB-EXT:RUN-PROGRAM: Bad file descriptor

### ISSUE THREAD

**Issue by Lovesan** [akovalenko/sbcl-win32-threads#1]
I've tried to build 1.0.47.9.273 with mingw+msys but noticed that some contribs failed, namely:
1. asdf-install
2. sb-bsd-sockets
3. sb-posix
4. sb-simple-streams

I've traced the problem to `sb-grovel` module, and then to `run-program` function.
`run-program` fails when `:output` parameter is a lisp stream, such as `sb-sys:*stdout*`

For some reason, this function fails only the first time. Subsequent calls do not throw any errors.

Btw, i've tried your precompiled binary just now.
This binary also possesses such a problem:
http://www.siftsoft.com/dl/sbcl-ci-exe-1.0.47.9.273.wth.kovalenko-x86.zip

**Comment by akovalenko** [comment]
Thank you for reporting. The bug is probably caused by migration from
lowio descriptors to OS-level handles.

I'm trying to fix it; meanwhile, there is a workaround that should help
if you're building from source: disabling target feature
:FDS-ARE-WINDOWS-HANDLES should make the bug disappear (if I've guessed
the source of problems correctly). It can be done by putting the
following expression into customize-target-features.lisp file:

(lambda (features)
  (remove :fds-are-windows-handles features))

## 

Regards, Anton Kovalenko
+7(916)345-34-02 | Elektrostal' MO, Russia

**Comment by akovalenko** [comment]
The problem with running external programs (and, consequently, with SB-GROVEL) is expected to disappear in the current build (1.0.47.9.274.wth.kovalenko). 

Not yet tested when _building_ on native windows.

**Comment by Lovesan** [comment]
I've managed to build this new version.
`run-program` function works as expected, thanks.

But, i've noticed that sb-simple-streams contrib failed.
Particularly, those tests
- create-read-mapped-file-1 ;; Read data via a mapped-file-simple-stream object.
-  file-position-5 ;; Test file position when opening with :if-exists :append

**Comment by akovalenko** [comment]
Problem with `sb-simple-streams` seems to be solved in the current version (1.0.47.18.277).

**Comment by Lovesan** [comment]
Build succeeded, and everything seems to work fine, thanks.
