### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by markokocic** [akovalenko/sbcl-win32-threads#11]
While trying to build the latest version on mingw I got the following error:

```
win32-os.c: In function 'os_init':
win32-os.c:1435:5: warning: implicit declaration of function '_controlfp' [-Wimplicit-function-declaration]
win32-os.c:1435:17: error: '_EM_INVALID' undeclared (first use in this function)
win32-os.c:1435:17: note: each undeclared identifier is reported only once for each function it appears in
win32-os.c:1435:29: error: '_MCW_EM' undeclared (first use in this function)
win32-os.c: In function 'os_map':
win32-os.c:2014:1: warning: label 'use_read' defined but not used [-Wunused-label]
make: *** [win32-os.o] Error 1
make: Leaving directory `/c/development/cvstree/sbcl/src/runtime'
markko@strah /c/development/cvstree/sbcl
$ gcc -v
Using built-in specs.
COLLECT_GCC=C:\MinGW\bin\gcc.exe
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/4.6.1/lto-wrapper.exe
Target: mingw32
Configured with: ../gcc-4.6.1/configure --enable-languages=c,c++,fortran,objc,obj-c++ --disable-sjlj-exceptions --with-d
warf2 --enable-shared --enable-libgomp --disable-win32-registry --enable-libstdcxx-debug --enable-version-specific-runti
me-libs --build=mingw32 --prefix=/mingw
Thread model: win32
gcc version 4.6.1 (GCC)
```

**Comment by akovalenko** [comment]
There was a bug in mingw. IIRC, both gcc and w32api have float.h, and a wrong one was included. It's fixed in debian (sid) cross-compiler packages of mingw-w64 by now, so an upgrade may help (though I'm not sure about 32-bit mingw release schedules...). It's possible that a downgrade to 4.5 or 4.4 might help as well.

Meanwhile, a possible workaround is to copy float.h (that which is in the same directory as windows.h) to some zzzfloat.h, and change SBCL's src/runtime/win32-os.c to include zzzfloat.h instead of float.h. I was unable to come up with a workaround that wouldn't be outright ugly (e.g. I could steal those definitions from float.h into SBCL), but if a clean build with that version of mingw is important to you, I'll take a deeper look into it. (Then the exact download link to mingw compiler distribution you're using would be beneficial).

**Comment by akovalenko** [comment]
Please try building current git head (93bd46a4). It turned out that the problematic call to _controlfp is not needed any more.

**Comment by markokocic** [comment]
It builds now.
From some preliminary testing it seems to work too.
Thanks.
